### ISSUE TITLE
关于线上文件

### ISSUE THREAD

**Issue by LBupup** [hql7/wl-bim-viewer#9]
[你好，请问线上文件需要做什么处理吗？为什么我换个别的线上文件就加载不出来了？下面是线上文件的地址：https://3dviewer.yungongchang.com/uploads/d279035e-0702-42fb-b861-a39264fe10b7/d279035e-0702-42fb-b861-a39264fe10b7/output/1/Model.svf

**Comment by hql7** [comment]
不用做处理，转化出来的文件夹不用动



在 2020-12-28 19:51:05，"LBupup" <notifications@github.com> 写道：

你好，请问线上文件需要做什么处理吗？为什么我换个别的线上文件就加载不出来了？

**Comment by LBupup** [comment]
我用的线上文件地址也是阿里云的服务器为什么访问会有跨域呢？

**Comment by LBupup** [comment]
请问线上项目需要设置访问权限吗？我这边提示无访问权限

**Comment by hql7** [comment]
设置公共读



在 2020-12-29 10:20:30，"LBupup" <notifications@github.com> 写道：

我用的线上文件地址也是阿里云的服务器为什么访问会有跨域呢？

**Comment by LBupup** [comment]
> 设置公共读 在 2020-12-29 10:20:30，"LBupup" <notifications@github.com> 写道： 我用的线上文件地址也是阿里云的服务器为什么访问会有跨域呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LBupup** [comment]
请问大佬有什么办法能够获取到模型的尺寸和体积吗？

**Comment by hql7** [comment]
这个倒是不晓得



在 2020-12-29 14:26:20，"LBupup" <notifications@github.com> 写道：

请问大佬有什么办法能够获取到模型的尺寸和体积吗？
